; Author: Sean Pesce

.code
extern export_locs:QWORD
GetFileVersionInfoA_wrapper proc
    jmp export_locs[0*8]
GetFileVersionInfoA_wrapper endp
GetFileVersionInfoByHandle_wrapper proc
    jmp export_locs[1*8]
GetFileVersionInfoByHandle_wrapper endp
GetFileVersionInfoExW_wrapper proc
    jmp export_locs[2*8]
GetFileVersionInfoExW_wrapper endp
GetFileVersionInfoSizeA_wrapper proc
    jmp export_locs[3*8]
GetFileVersionInfoSizeA_wrapper endp
GetFileVersionInfoSizeExW_wrapper proc
    jmp export_locs[4*8]
GetFileVersionInfoSizeExW_wrapper endp
GetFileVersionInfoSizeW_wrapper proc
    jmp export_locs[5*8]
GetFileVersionInfoSizeW_wrapper endp
GetFileVersionInfoW_wrapper proc
    jmp export_locs[6*8]
GetFileVersionInfoW_wrapper endp
VerFindFileA_wrapper proc
    jmp export_locs[7*8]
VerFindFileA_wrapper endp
VerFindFileW_wrapper proc
    jmp export_locs[8*8]
VerFindFileW_wrapper endp
VerInstallFileA_wrapper proc
    jmp export_locs[9*8]
VerInstallFileA_wrapper endp
VerInstallFileW_wrapper proc
    jmp export_locs[10*8]
VerInstallFileW_wrapper endp
VerLanguageNameA_wrapper proc
    jmp export_locs[11*8]
VerLanguageNameA_wrapper endp
VerLanguageNameW_wrapper proc
    jmp export_locs[12*8]
VerLanguageNameW_wrapper endp
VerQueryValueA_wrapper proc
    jmp export_locs[13*8]
VerQueryValueA_wrapper endp
VerQueryValueW_wrapper proc
    jmp export_locs[14*8]
VerQueryValueW_wrapper endp
end
